[2021-05-16 05:57:38,892] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Assignment1_Q2.CSV 2021-05-16T05:57:34.156252+00:00 [queued]>
[2021-05-16 05:57:38,945] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Assignment1_Q2.CSV 2021-05-16T05:57:34.156252+00:00 [queued]>
[2021-05-16 05:57:38,946] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 05:57:38,946] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-05-16 05:57:38,947] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 05:57:38,962] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): CSV> on 2021-05-16T05:57:34.156252+00:00
[2021-05-16 05:57:38,967] {standard_task_runner.py:52} INFO - Started process 64 to run task
[2021-05-16 05:57:38,978] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Assignment1_Q2', 'CSV', '2021-05-16T05:57:34.156252+00:00', '--job-id', '18', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpzn1e2un4', '--error-file', '/tmp/tmp8r183ak9']
[2021-05-16 05:57:38,979] {standard_task_runner.py:77} INFO - Job 18: Subtask CSV
[2021-05-16 05:57:39,137] {logging_mixin.py:104} INFO - Running <TaskInstance: Assignment1_Q2.CSV 2021-05-16T05:57:34.156252+00:00 [running]> on host afb0088131e3
[2021-05-16 05:57:39,383] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=GhaydaHyasat
AIRFLOW_CTX_DAG_ID=Assignment1_Q2
AIRFLOW_CTX_TASK_ID=CSV
AIRFLOW_CTX_EXECUTION_DATE=2021-05-16T05:57:34.156252+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-16T05:57:34.156252+00:00
[2021-05-16 05:57:39,384] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-16 05:57:39,385] {bash.py:158} INFO - Running command: psql postgresql://postgres:postgres@de_postgres:5432 -c "\copy loan_data_set to '/home/airflow/data/None.csv' csv header ;"
[2021-05-16 05:57:39,398] {bash.py:169} INFO - Output:
[2021-05-16 05:57:39,505] {bash.py:173} INFO - psql: FATAL:  password authentication failed for user "postgres"
[2021-05-16 05:57:39,506] {bash.py:177} INFO - Command exited with return code 2
[2021-05-16 05:57:39,549] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-16 05:57:39,552] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=Assignment1_Q2, task_id=CSV, execution_date=20210516T055734, start_date=20210516T055738, end_date=20210516T055739
[2021-05-16 05:57:39,667] {local_task_job.py:146} INFO - Task exited with return code 1
